import os
import time
import random

def cls():
    os.system('cls' if os.name=='nt' else 'clear')

def load():
    cls()
    print('Подождите, идёт загрузка\n[.........00%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*........05%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[**.......10%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[***......15%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[****.....20%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*****....25%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[******...30%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*******..35%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[********.40%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********45%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********50%.........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********55%*........]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********60%**.......]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********65%***......]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********70%****.....]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********75%*****....]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********80%******...]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********85%*******..]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********90%********.]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*********95%********.]')
    time.sleep(random.uniform(0.1,0.5))
    cls()
    print('Подождите, идёт загрузка\n[*******Готово!*******]')
    time.sleep(1)
    cls()